### ISSUE TITLE
Crossref and sblxref

### ISSUE THREAD

**Issue by SClarkWT** [dcpurton/biblatex-sbl#11]
What's the difference between the two? Is there a way to make it where ```crossref``` works as well? For people switching between styles frequently this may be an issue.

**Comment by dcpurton** [comment]
Biblatex supports a number of cross referencing fields natively, but none of them was quite suitable for what I needed with SBL.

* `crossref` connects two entries together and *inherits* fields from the entry cross referenced. If entries cross referencing to `crossref` are referenced more than `mincrossrefs` numer of times, it will appear in the biibliography.
* `xref` connects two entries together but *doesn't inherit* any fields. Again, the entry pointed to by `xref` will appear in the bibliography if entries cross referencing to it appear more than `mincrossrefs` times.
* `sblxref` doesn't inherit any fields but will always appear in the bibliography regardless of the value of `mincrossrefs`. It is used when what appears in the citation is radically different to what appears in the bibliography. This seems to happen a lot in the SBL handbook of style.
* `related` is used for things like reprints.

I could have used `xref` instead of `sblxref`, but there was not a way to control `mincrossrefs` independently for `xref` and `crossref` which would potentially lead to confusing behaviour.

Some of the special examples I've just finished make use of both `sblxref` and `crossref`.

It's not ideal, but the requirements of SBL seem quite peculiar in some cases, and I've found `sblxref` useful. I have added various keys for the `options` entry that can then control whether a record appears in the bibliography or list of abbreviations. Again the latest examples make extensive use of this feature.
