### ISSUE TITLE
Make SBLHS2 6.2.12 more like CMS?

### ISSUE THREAD

**Issue by folofjc** [dcpurton/biblatex-sbl#118]
I do not get why SBL chose to do section 6.2.12 like they do for bibliographic entries. Based upon the blog post [here](https://sblhs2.com/2017/03/23/citing-chapter-single-authored-work/), they reference CMS section 14.111 and 14.112. (I think there is a mistake in the blog post - SBLHS2 section 6.2.12 is not about multivolume works, but edited works. The examples in the blog post show that they mean edited works.) I am not sure what version of CMS they are referring to, but in CMS 17 (the only one I have) I think the sections are 14.106 and 14.107. I am only talking about edited works (which is what SBLHS2 6.2.12 is about), so that is CMS17 14.107. Here is what that looks like:

![Screenshot 2021-06-19 230046](https://user-images.githubusercontent.com/4741202/122655394-46c87d80-d152-11eb-92d5-6795cc238c55.png)

As you can see, this does not match SBLHS2. The pages come after the title of the volume, not before. I have no idea why SBL did it the way they did it, while at the same time referring to CMS?! CMS does not _specifically_ state that the pages have to come after (though the example implies it). However, here is what the 9th edition of Turabian (which follows CMS very closely) states:

![Screenshot 2021-06-19 230249](https://user-images.githubusercontent.com/4741202/122655444-87c09200-d152-11eb-9a12-3ded92e61793.png)

The Bibliography entries match, and the text is explicit.

I would like to implement this for `incollection` types in `biblatex-sbl`. I looked at trying to update the `chapter+pagesin` bibmacro in `biblatex-sbl.def` (based upon the `incollection` bibliography driver in `sbl.bbx`). It looks like the pages would need to be added to the `shortseries+number` macro? It should go before the publication data, but I am not sure if it should go before `note`. 

Any suggesions, @dcpurton? Thanks for all your help!

**Comment by dcpurton** [comment]
:) I can not say if they have made a mistake in their blog post, but they are consistent with their *Pages … in* use in the bibliography (See §6.2.12, §6.2.13, §6.2.22, §6.2.23, §6.3.3, etc.). They did this in both the first and second edition of their handbook. As far as I know CMS has never done this, so I can only assume that it's a deliberate decision. And I have not seen any example on their blog on in the handbook which does it like CMS. It's possible they refer to CMS in the blog post in reference to the note format, rather than the bibliography format.

SBL definitely doesn't always follow CMS and they seem to feel free to do their own thing. You could write to them I guess and ask for clarification.

My goal isn't to make an infinitely flexible style for `biblatex-sbl`, but implement what SBL wants as best I can.

I suggest you ask a question on tex.stackexchange.com about modifying `biblatex-sbl` to do what you want. I'll take a look in that context if moewe doesn't get to it first!

It would probably need the `incollection` driver to be changed I think. Note that this would have quite far reaching consequences, since `incollection` is used for various other `in*` entry types.

**Comment by folofjc** [comment]
Yeah, for sure SBLHS is consistent internally. I just have no idea why they did what they did ;) It just makes things more complicated for me! I had been using `biblatex-chicago` as I had already told you, and could get 90% of the way to my style guide. But man, the last 10% was a HUGE hassle trying to modify `biblatex-chicago`. So I thought I would try to do `biblatex-sbl` again. I never saw this in their examples until yesterday. Unfortunately, they are very common!! 

Does moewe use `biblatex-sbl`? I didn't know that What question can he not answer?! ;)

**Comment by dcpurton** [comment]
moewe doesn't use `biblatex-sbl`, but since he is one of the developers of `biblatex`, he can answer most questions on anything to do with `biblatex`.

**Comment by folofjc** [comment]
Yeah, I knew he was a developer of `biblatex`, that is why I was confused.

**Comment by folofjc** [comment]
For those interested, this answer works well for me: [tex.se](https://tex.stackexchange.com/a/602099/31561)
