### ISSUE TITLE
Branches and tags

### ISSUE THREAD

**Issue by baem2** [dcpurton/biblatex-sbl#16]
I am not a professional developer (and even worse, I am not even in science), so I have no idea how this is usually done. And I am happy with biblatex-sbl being in existence, which is the most important point.

Two things @maieul is doing with his LaTeX-reledmac package on github I particularly like: He makes new development changes in branches, not in the 'master' dir, so you always can download the stable version from 'master' (he merges the branches to master for each release). And secondly he adds a new tag for each release, so it is easy to go back and download an older release.

This just came to my mind when I saw that sbl 0.2 is not running on one of my machines due to the babel 3.0-requirement. Luckily I still had a tarball with v0.1, so it was not a problem.

**Comment by maieul** [comment]
I am quite pride to be cite for my dev methods ;-)

**Comment by dcpurton** [comment]
This is probably a good suggestion. I didn't really think about it until now since only one person was actually using it and I have not considered it stable enough for wider usage.

Having said that, with Git you can check out the repository at any point in its history, not just at specific tags. 

For example, the commit before the `entryclone` stuff was added can be browsed directly: 8499424db225c46ce859d84c062cca464463a000

The only problem is that there have been a lot of improvements and fixes since then.

**Comment by maieul** [comment]
tags is required to know the "official" release version.

**Comment by Nhapsie** [comment]
Hello Phillip, 

Thanks for your interest. I am the one using master since it’s inception, and thank God every time David updates it. Having said that, I do the following, without a problem: I download the master zip and make a copy of it, renaming it with the current date. I keep a few copies, just to be safe.

We have to remind ourselves to allow David to do what he does best, work on new citation formats and fixes. It’s a voluntary work. Now if he wants to improve on something else related to Git structure that’s up to him. 

The problem of the German and other languages is important but not top priority. Having said that, David will do the best he can presently,

Thanks for your understanding,
Carlos

**Comment by baem2** [comment]
I totally see your point, and I agree that the development of the sbl styles is top priority.

So I am closing here.
