### ISSUE TITLE
fullbibrefs=true not working with use of sblxref

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#31]
In the bibliography, full version optional style for @inreference does not format right when I use sblxref in my bib file. I think I have to update my name fields in bib file to match test file more accurately...

**Comment by Nhapsie** [comment]
Yes, I had to update my bib files in my reference manager. Test files are now using sblxref and crossref as well.

**Comment by dcpurton** [comment]
Do I need to do anything for this? What did you have before as your bib file?

**Comment by Nhapsie** [comment]
Just for now on, posting a new issue for change or addition in the test file is important, not only for problems. For example, we started off with crossref then replaced it with sblref, now we're using both. We got rid of revauthor and other fields to look more streamlined. If all these fields are not in sync between git test file and our local computer bib file they compile wrong, or even don't compile at all in the bibliography. I don't know if the wiki section would be a proper place for communicating changes rather than the issue section here. Let me know your thoughts.

**Comment by dcpurton** [comment]
The best place for this kind of thing is to create release notes for each version, summarising new features and any backwards incompatible changes. I know changes are a pain for you, but it's better to make them now while not many are using the style.

At present this has been difficult because there have been so many changes that it's been silly to wait for new releases - using the latest git version is best.

My plan is to start doing this when I first start uploads to CTAN. I think the style is not ready for this yet though (especially since bugs in the current CTAN version of `biblatex` break things). Hence, I've been marking the releases as "pre-release".

The next pre-release version will come when `biblatex` 3.4 is released. Things work well with this version.

The number of incompatible changes should not be major from now on. I'm pretty happy with the implementation I have for all the examples in the handbook. There may be some for the special examples section because I'm just guessing the best way to implement these, and someone who actually knows how they work might point this out...

**Comment by Nhapsie** [comment]
I agree that the test file is more robust now, and there is less change activity. It looks much better, especially the documentation, thanks a lot. I've been thinking about suggesting CTAN, but of course you already know that. When uploading to CTAN note that eventually there will be hundreds of questions posted here so it might be a problem for you. Post to CTAN with a different name than biblatex-sbl.

**Comment by dcpurton** [comment]
I think it's better to keep same name. I want people redirected here. Open Source works best when many people contribute. More people might ask questions, but also maybe more people will contribute.

The dev version now includes a Makefile to prepare a zip file for upload to CTAN.

**Comment by Nhapsie** [comment]
That's the spirit, thanks!

**Comment by dcpurton** [comment]
Plus, I'm not sure I share your optimism as to the number of biblical studies students who use LaTeX ;)

**Comment by Nhapsie** [comment]
yea? wait till I lead a presentation of this git and test file at an SBL convention for technology

**Comment by dcpurton** [comment]
Really? That would be cool.

**Comment by Nhapsie** [comment]
I plan on doing that next year or so when we have a stable CTAN upload and some more experience.
