### ISSUE TITLE
sbl-paper as package?

### ISSUE THREAD

**Issue by spencerclrk** [dcpurton/biblatex-sbl#38]
Thanks for putting together the sample paper!

Any way this can become a separate package as a .cls?

**Comment by dcpurton** [comment]
I'm considering this.

My hesitation is what makes most sense for `biblatex-sbl`
  - leave it as a stand-alone example as part of the documentation to `biblatex-sbl` (current option)
  - leave it as part of the documentation to `biblatex-sbl`, but strip the preamble out into a `.cls` or (more likely) a `.sty` file.
  - make it a totally separate package to `biblatex-sbl`, but hence dependent on `biblatex-sbl`
  - use the wiki attached to this github to build a repository of style files for various colleges and seminaries based on this a `.sty` file.
  - some combination of the above

A related question is how much do I put into the `.sty` file?
  - Should I add Greek and Hebrew support out of the box? This either reduces the flexibility of the file, since it would force the end user to use `xelatex` or `lualatex`, or alternatively increases the complexity by creating options to enable Greek and Hebrew.

**Comment by Nhapsie** [comment]
I think `sty` files or modules would offer more flexible options to be incorporated into or called from one's particular `cls`. To give an example, biblical languages is a must in many cases except for systematic theology. In this case an `sty` for biblical languages makes sense. In the preamble you would place the information about `xelatex`. Whatever extra we do here must be left as optional.

**Comment by SClarkWT** [comment]
My university uses the Student Supplement as is (thus my interest).

[SBTS](http://sbts.edu) — a local seminary — uses Turabian as primary, SBL for abbreviations and for specific issues that Turabian doesn't address. I'm not sure how much benefit this package would be for them. Would almost need to start with Turabian or Chicago and work from there. Their journal citations, for example, are:

> Dozeman, Thomas B. “Inner-Biblical Interpretation of Yahweh’s Gracious and Compassionate Character.” *Journal of Biblical Literature* 108, no. 2 (1989): 207– 23.

It wouldn't be terribly hard to modify the `sbl-paper` on a case-by-case basis for unique uses.

An included `.sty` or `.cls` file would be easiest, I think. But you could perhaps make it separate from `biblatex-sbl` and even allow for one's own biblatex style, but again, the occasions when someone would *need* `sbl-paper` without `biblatex-sbl` seem rare.

Greek/Heb support is a must. Could be a separate file, though, if needed.

**Comment by Nhapsie** [comment]
Clark! I visited your Git and it looks great, nice to know you're maintaining Fischer's. In fact, I produced the same stuff basically. Check out my template, under construction as well. [https://www.dropbox.com/s/av953su72xqjh5i/autemplate.pdf?dl=0]

**Comment by SClarkWT** [comment]
Thanks @Nhapsie ! Is your's intended for a thesis/dissertation or some school-specific stuff?

**Comment by Nhapsie** [comment]
I just uploaded some corrections. Yes, it's intended for thesis.

**Comment by dcpurton** [comment]
Check out the latest dev branch for `sbl-paper.sty`. `sbl-paper.tex` now shows how to use the package. Greek and Hebrew are also supported.

**Note:** There is an incompatibility between the `bidi` package and `biblatex` that means that it is not possible to track footnote citations separately from body citations. This is probably not a show stopper bug. It will potentially appear if you are using *idem* or *ibid* and interspersing `\parencite` and `\autocite` citations.

**Comment by Nhapsie** [comment]
I see, thanks for the info. We don't use `\parencite` in our seminary just one system of tracking, but for others this is good to know. The inclusion of new example for single volume dictionary in 6.3.6.2 of `biblatex-sbl-test.pdf` looks great.

The latest dev branc has good addition to `sbl-paper.tex`. Some observations: 1) omit "when a word processor such as Microsoft Word..." 2) add an example of hebrew transliteration in italics, such as this: `[tśʾw ʾt ʿwntykm]`

**Comment by dcpurton** [comment]
fixed in v0.7
