### ISSUE TITLE
Adding italics to transliterated text

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#42]
The question here relates to the font we have in the test file. How can I add italics to transliterated text? Look at the pic below: [tśʾw ʾt ʿwntykm]` I need to know the syntax, and whether SBLBibLit is keeping us from applying italics. AFAIK, this font does not allow italics. If that's the case which font shall we choose for Hebrew transliteration?  

<img width="345" alt="screen shot 2016-04-22 at 11 59 23 am" src="https://cloud.githubusercontent.com/assets/5918656/14761478/727aa068-0928-11e6-8155-6bf9880c5008.png">

**Comment by dcpurton** [comment]
You are correct. This is a font issue. I've used *Minion Pro* for the font in `sbl-paper.sty`. I chose this because this is the font used in the student supplement, and so it was useful for checking to make sure that spacing matched. However, *Minion Pro,* lacks many required glyphs from the Latin Extended-B Unicode block (as well as both half rings: 0x02BE, 0x02BF).

I could switch the font to *Linux Libertine O*. This is the font I have used in the other documentation files. This has two advantages: 1. It's a much nicer looking font, and 2. It's a free font, which is being actively developed and improved.

If I changed the font, then nothing special would need to be done to set transliterated text. Just use `\emph{tśʾw ʾt ʿwntykm}`.

The other option is to try and find a font that looks *similar* to your body text and change font when you need to do transliterated text. IMHO, this is suboptimal, since a change of font for latin characters is always obvious and looks ugly. Perhaps ultimately SBL will produce italic and bold variants for the SBLBibLit font and you could use this font for everything.

**Comment by Nhapsie** [comment]
The suboptimal option is not too bad, because I only use transliteration to mimic the quotation form used by the author. When I am using Hebrew it is never the transliterated form. For transliteration SBL Hebrew and Linux Libertine O work, as I just tested them. But I can't get the italics to work, because I am using a `\tl`custom command that you produced. What's the syntax to add italics?

**Comment by dcpurton** [comment]
Remove the `\tl{}' completely. All that did was provide a convenient way to change font. Instead of `\tl{}`, just use `\emph{}`, and your transliterated text will use italic Linux Libertine O.

**Comment by dcpurton** [comment]
I've updated the `sbl-paper` example files. Have a look.

**Comment by Nhapsie** [comment]
Oh, I see, thanks. But there's still a problem. The empty spaces in the transliteration, having accents with no consonants, come out with an empty box as follows. I know... this is a pain. 
![screen shot 2016-04-26 at 10 04 24 pm](https://cloud.githubusercontent.com/assets/5918656/14840595/2709edd4-0bfb-11e6-8ae8-a35db13dd0c3.png)

**Comment by dcpurton** [comment]
Something is wrong with your font set up. The boxes indicate that the font you are using is missing the half ring glyphs.

What do you get from this MWE (which gives correct output for me):

```TeX
\documentclass{article}
\usepackage{fontspec}
\setromanfont{Linux Libertine O}
\begin{document}
\emph{tśʾw ʾt ʿwntykm}
\end{document}
```

If it doesn't work, then maybe your copy of Linux Libertine O is old. Grab the latest from http://www.linuxlibertine.org/

**Comment by Nhapsie** [comment]
The MWE comes out right, like this: 
![screen shot 2016-04-26 at 10 44 33 pm](https://cloud.githubusercontent.com/assets/5918656/14841183/c6c0bbc8-0c00-11e6-8696-7bff3e22f283.png)

Which means something in my `cls` is off
