### ISSUE TITLE
Syntax for division of source

### ISSUE THREAD

**Issue by maieul** [dcpurton/biblatex-sbl#43]
Reading https://github.com/plk/biblatex/issues/424, I saw you used | to mark the division of source.

Maybe I will play for myself, but I think it will be better to kept the have the same system to mark division of source. And there is already a system for that, provided by https://www.ctan.org/pkg/biblatex-source-division

**Comment by maieul** [comment]
In this package, the syntaxe used is  `\cite[(Source division)pageref]{source}`

**Comment by dcpurton** [comment]
Ah! If had known of the existence of your package, it might have saved me a considerable amount of pain. I had trouble with expansion with splitting the `postnote` in two until someone pointed me to `xparse`. I simply invented the syntax of the pipe character as I needed something that probably wouldn't appear in either part.

Your syntax is more standard for latex and using `titleaddon` has some compatibility advantages. But how could I do something like this:

```TeX
\autocite[§3 (A I 11--17)|26]{disappearanceofsungod}
```

The parentheses stuff up your syntax. But I don't know how to get latex to produce them another way without entering mathmode which then changes the font.

**Comment by maieul** [comment]
in 

> \autocite[�3 (A I 11--17)|26]{disappearanceofsungod}

what does mean each part ?

**Comment by dcpurton** [comment]
:) I have no idea. It's one of the examples from the SBL handbook of style. I have an M.Div which is a graduate degree in theology. I never really needed to reference ANE texts, and not even classical ones beyond ANF ad NPNF.

The example given in the handbook is this:

---

### Citation

<html>&#8195;&#8195;&#8195;</html>12.  “The Disappearance of the Sun God,” §3 (A I 11–17) (Harry A. Hoffner Jr., *Hittite Myths,* ed. Gary M. Beckman, WAW 2 [Atlanta: Scholars Press, 1990], 26).

### Abbreviations

WAW<html>&#8195;&#8195;&#8195;</html>Writings from the Ancient World

### Bibliography

Hoffner, Harry A., Jr. *Hittite Myths.* Edited by Gary M. Beckman. WAW 2. Atlanta: Scholars Press, 1990.

---

Here's the page from the second edition of Hoffner, so it's page 27 instead of 26:

![disappear](https://cloud.githubusercontent.com/assets/6268044/15447980/f0d4d26a-1f91-11e6-9f59-f688a557bc75.png)

This shows what §3 (A I 11–17) refers to. My guess is that §3 and A I 11–17 are two different systems for referring to the same lines in the text. Perhaps the reference in parentheses refers to the original text and §3 the translation.

Either way, I can't make your `biblatex-source-division` package pass the parentheses through, as it gets confused about where the end of the argument comes.

This is my current bib implementation:

```
@book{hoffner:1990,
  author = {Hoffner, Jr., Harry A.},
  title = {Hittite Myths},
  editor = {Beckman, Gary M.},
  series = {Writings from the Ancient World},
  shortseries = {WAW},
  number = {2},
  location = {Atlanta},
  publisher = {Scholars Press},
  date = {1990}
}
@ancienttext{disappearanceofsungod,
  title = {The Disappearance of the Sun God},
  related = {hoffner:1990}
}
```

```TeX
\autocite[§3 (A I 11--17)|26]{disappearanceofsungod}

\printbiblist{abbreviations}

\printbibliography
```

It's simple and works well.

**Comment by dcpurton** [comment]
Ah! Just realised, I could use braces for your syntax:

```TeX
\autocite[({§3 (A I 11--17)})26]{dissappearanceofsungod}
```

I'll think about switching, but I still quite like my pipe character option :)

**Comment by dcpurton** [comment]
By the way, why did you decide to use the `titleaddon` field? What happens if the bib entry already uses this?

**Comment by maieul** [comment]
I decided to use the titleaddon field because I considered that the division of source could be considered as an extension of the title, as it is a subdivision of work. Also because good placed in the default style, so not need any modification.

If title addon field is used, it will be overread. But as I see no example of use of title addon I don't see any problem.
However, I use titleaddon field for books which are partially edited in one physical volume. For example in the "Source Chr�tiennes"

`````
@book{EvagreI-III,
	Annotator = {Laurent {Angliviel de la Beaumelle} and Guy Sabbah},
	Author = {{�vagre le Scholastique}},
	Date-Added = {2014-11-12 15:12:57 +0000},
	Date-Modified = {2014-11-12 15:18:35 +0000},
	Editor = {Bidez, Joseph and Parmentier, L�on},
	Introduction = {Guy Sabbah},
	Number = {542},
	Series = {Sources Chr�tiennes},
	Shortseries = {SC},
	Title = {Histoire eccl�siastique},
	Titleaddon = {Livres I-III},
	Translator = {Festugi�re, Andr�-Jean and Bernard Grillet and Guy Sabbah}}
``````

**Comment by maieul** [comment]
I think you should use \mkbibparens instead of directly (), because would manage parens in parens -> brackets.

**Comment by dcpurton** [comment]
I think it is worth changing my syntax. I will use your syntax, but with a different implementation since using `titleaddon` creates some problems for SBL style.

**Comment by maieul** [comment]
As implementation is for your style, that doesnot matter. But having the same syntax while facilitate migration from one style to an other one.
