### ISSUE TITLE
biblatex-sbl project

### ISSUE THREAD

**Issue by SClarkWT** [dcpurton/biblatex-sbl#5]
Hi David,

Thank you so much for putting out the .bst from years ago. I ported it over to SBLHS2 when it came out in 2014 and it has been so helpful.

Unfortunately for myself, I unwittingly began biblatex-sbl without knowledge that you were doing the same. I haven't seen much on the web about SBL/LaTeX since Robert Fischer went MIA. He actually provided me with sblref and the .bst, if I remember correctly.

The key difference is that I am modifying biblatex-chicago so your code is immensely cleaner (although with the possible disadvantage it may not work in unusual cases). Here's what I have so far:

[https://github.com/SClarkWT/biblatex-sbl2](biblatex-sbl2)
^^ posted for your benefit, not as a competing platform.

I ran some tests with your package and really appreciate what you're doing here. There's several things I haven't figured out just yet that you completed. That being said, do you have any interest in collaboration on the project(s)? I'd love to assist you with some of the load. It'd be great to have a stable CTAN release eventually.

Thanks for your work,

Spencer

**Comment by dcpurton** [comment]
Hi Spencer,

Your work looks great! A pity we both spent time doing the same thing! However, you have documentation!

I did consider using biblatex-chicago as a base, but this is the first time I've done anything with biblatex (someone asked me to port my bibtex stuff to biblatex), and I found the chicago style complicated! I figured I'd learn better by designing from the ground up based on the standard style. Though you are right that falling back on chicago will give better results than falling back on the standard style.

I have now actually completed code to cover every example given in the SBLHS and the student supplement, but I haven't pushed things to github yet because I'm not quite happy with how I've implemented some of the special examples from section 6.4.

I'd certainly be interested in collaborating as I don't use the style myself much. I've finished studies and I'm not looking to do further study at the moment, so I just do it as a hobby really. I have fixed bugs as the person who asked me to make it has found problems.

How are you thinking that collaboration might work?

There's a number of things I'd like to eventually get round to checking and adding:

* making sure there's no hard-coded English strings
* making sure that it can be built with as many flavours of LaTeX as possible (I think there are some hard-coded UTF-8 characters and there are some issues with LuaLaTeX I've come across)
* adding an essay class matching what is recommended in the student supplement (you've done something a it like this in your example)
* write proper documentation
* discuss with someone else some of the decisions I've made when the SBLHS is not clear.

I'll try and get the remaining examples into github as soon as I can and create an initial tag that supports all the SBL examples.

David

**Comment by SClarkWT** [comment]
Hey David,

Since your work is furthest along, it will probably be best to work from yours. When you finish up with the examples I can help with extensive testing and see if there's any code from Chicago that's needed to enhance the package's flexibility (i.e. Chicago has extensive localization already that may be a good starting place for multi-lingual support). 

After that I don't mind merging your examples with the documentation I have partially completed to save some time. I don't have any experience with LuLaTeX so I may not be much help in that area.

Robert Fischer built an essay class years ago that I have been maintaining privately ( [sbl-paper](http://github.com/SClarkWT/sbl-paper)). It needs some TOC work and support for appendices. Feel free to look into it and make suggestions.

According to the Introduction, it seems like SBLHS2 may revert to Chicago (/Turabian?) when something is unclear (p. 1).

Those special examples are always fun... I can help more when you get that code out.


Spencer

**Comment by Nhapsie** [comment]
Hi Spencer. 

Not long ago I persuaded David to jump into BibLaTex, and he’s done a wonderful job so far. My role is helping test the biblatex-sbl project. Actually I am using it for my thesis. I use MacTex 2015 with XeLaTeX without a problem. So welcome aboard! 

Carlos

**Comment by SClarkWT** [comment]
Carlos!

Props to you for committing to alpha software for your thesis :+1:  I will start mine sometime in 2017 and hope to have all the LaTeX done so things just work when time comes to write. Looking forward to assisting when I can.

**Comment by Nhapsie** [comment]
Thanks for your support, Spencer, all the best to you!
