### ISSUE TITLE
Suppress footmisc{bottom}

### ISSUE THREAD

**Issue by lenrsmith** [dcpurton/biblatex-sbl#56]
Is there an easy way to suppress the footmisc{bottom} setting? My institutions likes for footnotes to hug the text rather than the bottom of the page.

Love the work, btw.

**Comment by dcpurton** [comment]
You mean when using `sbl-paper.sty`?

I don't think there is an easy way at the moment. You could try asking on tex.stackexchange.

I suggest making a copy of `sbl-paper.sty`, renaming it to `your-institution-paper.sty` and remove the `bottom` option from `footmisc`.

I'm currently re-implementing  `sbl-paper.sty` to use the `memoir` class which will make this kind of thing much easier. But I'm not finished yet.

The current version of `sbl-paper.sty` was really meant to be an example of how you might use  `biblatex-sbl`, rather than a generic term paper solution. But it's clearly getting used more than I thought it would.

**Comment by lenrsmith** [comment]
That makes sense, and I can certainly do that. I look forward to seeing your new work. You have to be careful what you build as a demo, though; you never know who may coop it and start using it in production :-)

Thanks for putting all of this together. I’ve dabbled with Latex since my seminary days, and now I’m planning to use it for papers and a dissertation. It is encouraging to see some new development going on.
