### ISSUE TITLE
The Full History of a Translated Volume (6.2.5)

### ISSUE THREAD

**Issue by Nhapsie** [dcpurton/biblatex-sbl#59]
There are complications when editors are added to this reference type. The abbreviation for "editors" should be "eds" and not "ed". Also, the title is replaced by the editors when compiled.

**Comment by dcpurton** [comment]
I need a full MWE example for this as I'm not sure exactly where you are adding in editors. (Actually, it's always best to include a MWE for bug reports even if you think it's obvious.)

**Guess:** If you are seeing

> Author, *Title,* ed. First Editor and Second Editor (Location: Publisher, Year).

then this is correct. In this case, *ed.* is short for *edited by* (as seen in the bibliography) , not *editors*.

See 6.2.12 for an example.

**Comment by Nhapsie** [comment]
`%-*- program: xelatex -*-
%-*- program: biber -*-
%-*- program: xelatex -*-

\listfiles
\documentclass{article}
\usepackage[style=sbl]{biblatex}
\addbibresource{Untitled.bib}
\begin{document}

\cite[91--95]{Saussure2009}.

\printbiblist{abbreviations}
\printbibliography
\end{document}`

`Bib file`
`@book{Saussure1916,
author = {de Saussure, Ferdinand},
editor = {Bally, Charles and Sechehaye, Albert},
title = {Cours de Linguistique Générale},
location = {Lausanne and Paris},
date = {1916},}

@book{Saussure2009,
author = {de Saussure, Ferdinand},
editor = {Bally, Charles and Sechehaye, Albert},
title = {Course in General Liguistics},
translator = {Harris, Roy},
location = {Peru, Illinois},
publisher = {Open Court},
related = {Saussure1916},
relatedtype = {translationof},
date = {2009},}`

**Comment by dcpurton** [comment]
You need to include `relatedoptions = {skipbib,useeditor=false}` in `Saussure2009`. What happens is that the author is dropped in the related entry because it's the same as the primary author. But then the editor becomes primary and so is moved ahead of the title.

I think I can probably make this happen automatically, because it is a bit unexpected.

For the moment, here's a MWE with the editor in the right place:

```TeX
\documentclass{article}
\usepackage[style=sbl]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{Saussure1916,
  author = {de Saussure, Ferdinand},
  editor = {Bally, Charles and Sechehaye, Albert},
  title = {Cours de Linguistique Générale},
  location = {Lausanne and Paris},
  date = {1916}
}
@book{Saussure2009,
  author = {de Saussure, Ferdinand},
  editor = {Bally, Charles and Sechehaye, Albert},
  title = {Course in General Liguistics},
  translator = {Harris, Roy},
  location = {Peru, Illinois},
  publisher = {Open Court},
  related = {Saussure1916},
  relatedtype = {translationof},
  relatedoptions = {skipbib,useeditor=false},
  date = {2009}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\pagestyle{empty}
\begin{document}
\cite[91-95]{Saussure2009}.
\printbiblist{abbreviations}
\printbibliography
\end{document}
```

![temp05](https://user-images.githubusercontent.com/6268044/31847898-a524ace6-b66c-11e7-8387-023d06ed2e80.png)

**Comment by dcpurton** [comment]
Paris ought to show up... That's weird. I'll look into that one further.

**Comment by dcpurton** [comment]
Oh! I remember why multiple locations don't show up.

According to **§6.1.4.2 Place of Publication**:

> If the title or copyright page lists more than one city, only the first city should ordinarily
be used in the bibliography and notes (see CMS §14.135).

When you have multiple publishers and locations, the format is:

> Location1: Publisher1; Location2: Publisher2

Since the handbook states you don't need to specify multiple locations for a single publisher, you can have as many publishers as you want:

> Publisher1; Publisher2; Publisher3; …

But Locations must be matched with a publisher (unless no publisher listed, but still only the first location will be printed).

I did this because if you have (say) 2 publishers and 3 locations in your bib entry, it's not possible for the style to work out which publisher has the two locations. i.e., is it meant to be:

1. Location1 and Location 2: Publisher 1; Location 3: Publisher 2
or
2. Location1: Publisher 2; Location 2 and Location 3: Publisher 2

Given this, if you want to override the style and have two (or more) locations printed, then the right way to do it is to treat them as a single location in your bib entry.

You do this by specifying `location = {{Lausanne and Paris}}`

**Comment by dcpurton** [comment]
This is not to say that there isn't a better way of doing this, of course. Open to suggestions.

**Comment by Nhapsie** [comment]
1.  `relatedoptions = {skipbib,useeditor=false}` in `Saussure2009` worked well. In my long project it did not, but that's not a problem because I deleted the editors of `Saussure1916` since it's redundant. Thanks for the nice MWE. 
2. Yes, I remember now. `biblatex-sbl` continues to behave correctly even when we forget things.
