### ISSUE TITLE
Page numbers for articles

### ISSUE THREAD

**Issue by lenrsmith** [dcpurton/biblatex-sbl#60]
I have been unable to sort out where my problem lies, so I am not convinced that it has anything to do with this package. I need to cite specific page numbers within articles, but I am getting footnotes with the entire page range from the BibTex entry. Here is how I am citing the content: 

```\cite[179]{Wilson:1975aa}```

The result looks like

> Robert R. Wilson, “The Old Testament Genealogies In Recent Research.,” Journal of Biblical Literature 94.2 (1975): 169–89.

I would use `autocite`, but I am using it in a footnote with other citations. The whole citation should look like this:

> 6. Wilson, Genealogy and History in the Biblical World, 9. Yigal Levin, “Understanding Biblical Genealogies,” Currents in Research 9 (2001): 12. Robert R. Wilson, “The Old Testament Genealogies In Recent Research.,” Journal of Biblical Literature 94.2 (1975): 179.

I've tried the following approaches with the exact same results:
```\footnote{\cite[9]{Wilson:1977aa}. \cite[12]{Levin:2001aa}. \cite[179]{Wilson:1975aa}.} ```
```\autocites[9]{Wilson:1977aa}[12]{Levin:2001aa}[179]{Wilson:1975aa}```

**Comment by dcpurton** [comment]
This is by design. SBL requires the full page range to be specified for the first citation. You will get the specified page for subsequent citations.

You can override this behaviour by passing `citepages=omit` to `biblatex`. Other options for this are `sbl` (default), `permit`, and `separate`.

`permit` will give you the specified page in parentheses after the page range. e.g., 168–89 (179). `separate` includes the `thiscite` string in the parentheses following the page range. e.g., 169–89 (esp. 179).

See the `biblatex-sbl` manual for more details and examples on using the `citepages` option.

**Comment by lenrsmith** [comment]
Thanks, David. I'm still getting my wrapped around SBL style, so this is one of those 'duh' moments.

**Comment by dcpurton** [comment]
No worries!
